[project]
name = "applied-ai-health-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "requests>=2.32.5",
    "docling>=1.0.0",
    "langchain-text-splitters>=0.3.0",
]
